baseURL: https://romankurnovskii.com/
title: Roman Kurnovskii

# manual theme update or gitsubmodules
# theme: hugo-theme-yalla

# update/install with Hugo Modules
module:
  imports:
    path: github.com/romankurnovskii/hugo-theme-yalla
theme: github.com/romankurnovskii/hugo-theme-yalla

defaultContentLanguage: ru
defaultContentLanguageInSubdir: true
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean.

paginate: 10
copyright: >
  &copy; 2022 <a href="https://romankurnovskii.com">Roman Kurnovskii</a> personal page
enableEmoji: true
enableGitInfo: true
summaryLength: 75

# Uncomment for google analytics
googleAnalytics: G-26F2C5ZR4Y

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    codeFences: false
    noClasses: false
    guessSyntax: true

    anchorLineNos: false
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noHl: false
    style: monokai
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: never
  writeStats: false

params:
  enableInlineShortcodes: true
  enableRobotsTXT: true

sitemap:
  changefreq: always
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  SearchIndex:
    baseName: search # creates search.json for each language
    mediaType: application/json

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex

ignoreErrors: ["error-remote-getjson"]
