baseURL: https://romankurnovskii.com/
title: Roman Kurnovskii

# manual theme update or gitsubmodules
theme: hugo-theme-yalla

defaultContentLanguage: ru
defaultContentLanguageInSubdir: true

pagination:
  disableAliases: false
  pagerSize: 13

copyright: >
  &copy; 2025
enableEmoji: true
enableGitInfo: true
summaryLength: 80

Services:
  GoogleAnalytics:
    ID: G-26F2C5ZR4Y

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    codeFences: true
    noClasses: true # set false use custom css
    guessSyntax: true
    anchorLineNos: true #Configure anchors on line numbers. Valid values are true or false
    lineanchors: prefix
    lineNoStart: 1
    lineNos: false # line numbers
    lineNumbersInTable: true
    noHl: false
    style: friendly # nord rose-pine-dawn  autumn monokailight lovelace emacs tango friendly manni catppuccin-latte  # https://xyproto.github.io/splash/docs/
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: never
  writeStats: false

params:
  enableInlineShortcodes: true
  enableRobotsTXT: true

sitemap:
  changefreq: always
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  SearchIndex:
    mediaType: application/json
    # baseName: search # creates search.json for each language
    baseName: searchindex # creates search.json for each language
    isPlainText: true
    notAlternative: true

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex

ignoreErrors: ["error-remote-getjson"]

staticDir: # save here files for posts: pdf, img etc
  - static
  - static_files
