ru:
  languageCode: ru
  languageName: Русский

en:
  languageCode: en
  languageName: English
  menu:
    main:
      - name: Notes
        url: /posts/
        weight: 2
      - name: Research
        url: /p/publications
        weight: 4
      - name: Links
        url: https://rom8ski.notion.site/Pub-da00c595e6774e3da994be193dcde653
        weight: 5