ru:
  languageCode: ru
  languageName: РУ

en:
  languageCode: en
  languageName: EN
  menu:
    main:
      - name: Notes
        identifier: notes
        url: /posts/
        weight: 2
      - name: Roadmaps
        identifier: roadmaps
        url: /categories/roadmaps/
        weight: 2
      - name: Apps
        url: apps/
        weight: 5

      # Under Notes
      - name: AWS
        identifier: aws
        url: /categories/aws/
        parent: notes
        weight: 201
      - name: OS
        identifier: os
        url: /categories/os/
        parent: notes
        weight: 202
      - name: Programming
        identifier: programming
        url: /categories/programming/
        parent: notes
        weight: 203
      - name: Cheat Sheets
        identifier: cheatsheet
        url: /categories/cheatsheet/
        parent: notes
        weight: 204
      - name: Links
        identifier: links
        url: /en/p/links/
        parent: notes
        weight: 205

      # Notes -> OS ->
      - name: Docker
        identifier: docker
        url: /categories/docker/
        parent: os
      - name: Linux
        identifier: linux
        url: /categories/linux/
        parent: os
      - name: Mac
        identifier: macos
        url: /categories/macos/
        parent: os

      # Notes -> AWS ->
      - name: AWS Developer Associate
        identifier: aws-developer
        url: /en/tracks/aws-certified-developer-associate/
        parent: aws

      # Notes -> Programming ->
      - name: Algorithms
        identifier: algorithms
        url: /en/tracks/algorithms-101/
        parent: programming
        weight: 301
      - name: Python
        identifier: python
        url: /categories/python/
        parent: programming
      - name: JavaScript
        identifier: javascript
        url: /categories/javascript/
        parent: programming
      - name: Hugo
        identifier: hugo
        url: /categories/hugo/
        parent: programming

      # Roadmaps ->
      - name: Algorithms101
        identifier: algorithms-101
        url: /en/tracks/algorithms-101/
        parent: roadmaps
      - name: AWS Developer Associate
        identifier: aws-developer-roadmaps
        url: /en/tracks/aws-certified-developer-associate/
        parent: roadmaps
      - name: Диссертация [RU]
        identifier: rudisser
        url: ./../ru/tracks/disser/
        parent: roadmaps

