ru:
  languageCode: ru
  languageName: Русский

en:
  languageCode: en
  languageName: English
  menu:
    main:
      - name: Notes
        url: /posts/
        weight: 2
      - name: Apps
        url: apps/
        weight: 5
