ru:
  languageCode: ru
  languageName: Русский

en:
  languageCode: en
  languageName: English
  menu:
    main:
      - name: Notes
        url: /posts/
        weight: 2
      - name: Photos
        url: categories/photos/
        weight: 5

nodefault:
  languageCode: nodefault
  languageName: 