ru:
  languageCode: ru
  languageName: РУ

en:
  languageCode: en
  languageName: EN
  menu:
    main:
      - name: Notes
        identifier: notes
        url: /posts/
        weight: 2
      - name: Apps
        url: apps/
        weight: 5

      - name: AWS
        identifier: aws
        url: /categories/aws/
        parent: notes
        weight: 201
      - name: OS
        identifier: os
        url: /categories/os/
        parent: notes
        weight: 202
      - name: Programming
        identifier: programming
        url: /categories/programming/
        parent: notes
        weight: 203
      - name: Cheat Sheet
        identifier: cheatsheet
        url: /categories/cheatsheet/
        parent: notes
        weight: 204
      - name: Docker
        identifier: docker
        url: /categories/docker/
        parent: os
      - name: Linux
        identifier: linux
        url: /categories/linux/
        parent: os
      - name: Mac
        identifier: macos
        url: /categories/macos/
        parent: os

      - name: Python
        identifier: python
        url: /categories/python/
        parent: programming
      - name: JavaScript
        identifier: javascript
        url: /categories/javascript/
        parent: programming
      - name: Hugo
        identifier: hugo
        url: /categories/hugo/
        parent: programming
