main:
    - name: Заметки
      identifier: notes
      url: /posts/
      weight: 2
    - name: Руководства
      # url: /series/Руководства/
      url: /categories/roadmaps/
      weight: 3
    - name: Приложения
      url: apps/
      weight: 5
    - name: Публикации
      url: /p/publications
      weight: 8

    - name: Links
      identifier: links
      url: /en/p/links/
      parent: notes
      weight: 201


# eng menu in languages