main:
    - name: Заметки
      url: /posts/
      weight: 2
    - name: Руководства
      url: /series/Руководства/
      weight: 3
    - name: Треки
      url: /categories/треки/
      weight: 4
    - name: Публикации
      url: /p/publications
      weight: 5
    - name: Ссылки
      url: https://rom8ski.notion.site/Pub-da00c595e6774e3da994be193dcde653
      weight: 8


# eng menu in languages