main:
    - name: Заметки
      identifier: notes
      url: /posts/
      weight: 2
    - name: Руководства
      # url: /series/Руководства/
      url: /categories/roadmaps/
      weight: 3
    - name: Приложения
      url: apps/
      weight: 5
    - name: Публикации
      url: /p/publications
      weight: 8

    # notes
    - name: Links
      identifier: links
      url: /en/p/links/
      parent: notes
      weight: 201
    - name: EN
      identifier: enposts
      url: /en/posts/archive/
      parent: notes
      weight: 202

    # notes/en
    - name: Algorithms
      identifier: enalgorithms
      url: /en/docs/algorithms-101/
      parent: enposts
      weight: 301



# eng menu in languages