main:
    - name: Заметки
      url: /posts/
      weight: 2
    - name: Руководства
      url: /series/Руководства/
      weight: 3
    - name: Треки
      url: /categories/треки/
      weight: 4
    - name: Приложения
      url: apps/
      weight: 5
    - name: Публикации
      url: /p/publications
      weight: 8

# eng menu in languages