main:
    - name: Заметки
      url: /posts/
      weight: 2
    - name: Руководства
      url: /series/Руководства/
      weight: 3
    - name: Треки
      url: /categories/треки/
      weight: 4
    - name: Публикации
      url: /p/publications
      weight: 5
    - name: Фото
      url: categories/photos/
      weight: 8


# eng menu in languages