main:
    # - name: About
    #   url: '#about'
    #   weight: 1
    - name: Заметки
      url: /posts/
      weight: 2
    - name: Roadmap
      url: /docs/
      weight: 3
    - name: Публикации
      url: /p/publications
      weight: 4
    - name: Ссылки
      url: https://rom8ski.notion.site/Pub-da00c595e6774e3da994be193dcde653
      weight: 5
    # - name: Docs
    #   url: /docs/
    #   weight: 3