main:
  # - name: About
  #   url: '#about'
  #   weight: 1
  - name: Заметки
    url: /posts/
    weight: 2
  - name: Публикации
    url: /p/publications
    weight: 3
  - name: Ссылки
    url: https://roman-k.notion.site/Pub-da00c595e6774e3da994be193dcde653
    weight: 4
  # - name: Docs
  #   url: /docs/
  #   weight: 3