main:
  # - name: About
  #   url: '#about'
  #   weight: 1
  - name: Заметки
    url: /posts/
    weight: 2
  - name: Публикации
    url: /p/publications
    weight: 3
  # - name: Docs
  #   url: /docs/
  #   weight: 3