mainSections:
  - posts
description: Роман Курновский
repoEditURL: https://github.com/romankurnovskii/romankurnovskii.github.io/edit/main/
repoURL: https://github.com/romankurnovskii/romankurnovskii.github.io

dateFormat: 2006-01-02

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon: images/icon.png
publisherName: Roman Kurnovskii
publisherLogo:

highlight:
  handler: highlightjs

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

comment:
  # Options: disqus, commento, valine and utterances.
  handler: opencomments

  opencomments:
    server: https://eyt4njm3se.execute-api.eu-west-1.amazonaws.com/comments
    # server: https://opencomments.herokuapp.com/comments
    # serverLocal: http://127.0.0.1:5000/comments
    # server: http://127.0.0.1:5000/comments

  # telegram: #comments.app
  #   siteid: # e.g. Qu__K123

  # disqus:
  #   shortname:

  # utterances:
  #   # Browse https://utteranc.es/ to see the options available.
  #   repo: https://github.com/romankurnovskii/romankurnovskii.github.io
  #   issue-term: pathname
  #   theme: github-light

  # commento:
  #   # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
  #   url:

  # valine:
  #   # Browse https://valine.js.org/en/configuration.html to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `appId` should be written as `app-Id` or other acceptable formats.
  #   app-Id:
  #   app-Key:

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme:
  #   flowchart:
  #     diagram-padding:

analytic:
  yandexMetrika: 87734724

homeColorButtons:
  show: true
  btn1Title: Python
  btn1Url: categories/python/
  btn1Style:
  btn2Title: JavaScript
  btn2Url: categories/javascript/
  btn2Style:
  btn3Title: Hugo
  btn3Url: categories/hugo/
  btn3Style:
  btn4Title: Linux
  btn4Url: categories/linux/
  btn4Style:
    
shareButtons:
  icon: solid # normal(default) solid circle solidcircle
  size: small
  networks:
    - email
    - facebook
    - vk
    - linkedin
    - twitter
    - hackernews
    - reddit
    - whatsapp
    - telegram