# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Eureka"
license = "Apache 2.0"
licenselink = "#"
description = "Eureka is a feature-rich and highly customizable Hugo theme."
homepage = "https://romankurnovskii.github.io/"
tags = ["blog", "Responsive", "Simple", "Personal", "Light", "Dark", "Mobile", "Fast", "Disqus", "Google analytics", "Syntax highlighting", "Highlighting", "Multilingual", "Modern", "Font awesome", "Fontawesome", "Documentation", "Docs", "Seo", "accessible"]
features = ["Blog", "Responsive", "Documentation", "Light", "Dark"]
min_version = "0.74.0"

authors = [
  {name = "Roman Kurnovskii", homepage = "https://romankurnovskii.github.io/"},
]
