name: comments add

on:
  workflow_dispatch:
    inputs:
      url_path:
        description: The path to page
        required: true
      message:
        description: 'test check'
        required: true

jobs:
  predeploy:
    runs-on: ubuntu-20.04
    steps:
      
      # - name: setup branch
      #   uses: actions/checkout@v3

      # - name: create branch comments
      #   run: |
      #     git config --global user.email "test@test.com"
      #     git config --global user.name "test"
      #     git status
      #     echo "working on file"
      #     git checkout comments || git checkout -b comments
      #     cd $(pwd)/content/${{ github.event.inputs.url_path }}
      #     mv comments.json comments.json.bak || echo "{}" > comments.json.bak
      #     jq '. |= . + {"b": "${{ github.event.inputs.message }}" }' comments.json.bak  >| comments.json
      #     rm -rf comments.json.bak
      #     git add .
      #     git commit -m "add comment"
      #     git push --set-upstream origin comments

      - name: check inputs
        run: |
          echo "inputs print"
          echo "${{ github.event.inputs.message }}"
          pwd

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: comments

      - name: Add comment
        env: 
          COMMENTS_FILE: comments.json
          COMMENT_MESSAGE: "${{ github.event.inputs.message }}"
        run : |
          echo "checkout print"
          echo $COMMENT_MESSAGE
          echo "${{ github.event.inputs.url_path }}"
          cd $(pwd)/content/${{ github.event.inputs.url_path }}
          pwd
          ls -la
          
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git status

          # git checkout comments || git checkout -b comments
          git status

          echo "working on file"
          # mv comments.json comments.json.bak || echo "{}" > comments.json.bak
          # jq '. |= . + {"$(date +%s)": "${{ github.event.inputs.message }}" }' comments.json.bak  >| comments.json
          # rm -rf comments.json.bak

          test $COMMENTS_FILE || echo "[]" > $COMMENTS_FILE 

          echo --file_name=$COMMENTS_FILE --author=AUTHOR --message="$COMMENT_MESSAGE"
          wget https://raw.githubusercontent.com/romankurnovskii/comm/main/add_comment.py && (python add_comment.py --file_name=$COMMENTS_FILE --author=AUTHOR --message="$COMMENT_MESSAGE"; rm add_comment.py)
          rm -rf p.py

          ls -la

          git add .
          git commit -m "add comment"
          git push

          # rm -rf comments.json.bak
          # # git config pull.rebase true
          # # git branch -d comments ||  echo "removed"
          # git rebase --skip
          # mv comments.json comments.json.bak
          # jq '. |= . + {"$(date +%s)": "${{ github.event.inputs.message }}" }' comments.json.bak  >| comments.json
          # git add comments.json
          # git commit -m "add comments"
          # git push --set-upstream origin comments



