name: comments add

on:
  workflow_dispatch:
    inputs:
      url_path:
        description: The path to page
        required: true
      message:
        description: 'test check'
        required: true

jobs:
  predeploy:
    runs-on: ubuntu-20.04
    steps:
      - name: check inputs
        run: |
          echo "inputs print"
          echo "${{ github.event.inputs.message }}"
          pwd

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Add comment
        run : |
          echo "checkout print"
          echo "${{ github.event.inputs.message }}"
          pwd
          url_path=${{ github.event.inputs.url_path }}
          echo $(url_path)
          cd $(pwd)/content/$(url_path)
          pwd
          ls -la
          mv comments.json comments.json.bak
          jq '. |= . + {"a": "33"}' comments.json.bak  >| comments.json
          git add comments.json
          git commit -m "add comments"
          git push origin main



