name: comments add

on:
  workflow_dispatch:
    inputs:
      url_path:
        description: The path to page
        required: true
      message:
        description: 'test check'
        required: true

jobs:
  predeploy:
    runs-on: ubuntu-20.04
    steps:
      # - name: check inputs
      #   run: |
      #     echo "inputs print"
      #     echo "${{ github.event.inputs.message }}"
      #     pwd

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Add comment
        run : |
          echo "checkout print"
          echo "${{ github.event.inputs.message }}"
          echo "${{  github.event.inputs.url_path }}"
          cd $(pwd)/content/${{ github.event.inputs.url_path }}
          pwd
          ls -la
          
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git status

          git checkout comments || git checkout -b comments
          git status

          mv comments.json comments.json.bak || echo "{}" > comments.json.bak
          jq '. |= . + {"b": "${{ github.event.inputs.message }}" }' comments.json.bak  >| comments.json
          rm -rf comments.json.bak


          # rm -rf comments.json.bak

          # # git config pull.rebase true
          # # git branch -d comments ||  echo "removed"
          # git checkout comments || git checkout -b comments
          # git rebase --skip
          # mv comments.json comments.json.bak
          # jq '. |= . + {"b": "${{ github.event.inputs.message }}" }' comments.json.bak  >| comments.json
          # git add comments.json
          # git commit -m "add comments"
          # git push --set-upstream origin comments



