name: Deploy github pages

on:
  push:
    branches:
      - main # Set a branch to deploy

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    if: ${{ contains(github.event.head_commit.message, 'nobuild') != true }} # do not build if 'nobuild' in commit message
    runs-on: ubuntu-20.04

    steps:
      - name: init step
        run: echo "Commit message" ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v3
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 100 # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.SSH_REPO }} # set for this repo and theme repo. repo settings->Secrets. Created in Settings->Developer settings

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Install npm packages
        run: npm i

      - name: Create search indexes
        run: npm run hugo-lunr-ml

      - name: Install pip packages
        run: pip install -r requirements.txt

      - name: Convert Notebooks
        run: |
          for notebook in $(find static_files/jupyter -name "*.ipynb"); do
            jupyter nbconvert --to html "$notebook"
          done

      - name: Build
        env: # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --minify

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
