name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    if: contains(${{ github.event.head_commit.message }}, 'nobuild') != true # do not build if 'nobuild' in commit message
    runs-on: ubuntu-20.04

    steps:
      - name: init step
        run: echo "Commit message" ${{ github.event.head_commit.message }}
        
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod
          token: ${{ secrets.SSH_REPO }} # set for this repo and theme repo. repo settings->Secrets. Created in Settings->Developer settings

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'
          extended: true

      - name: Install packages
        run: npm i

      - name: Create search indexes
        run: npm run hugo-lunr-ml

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
